---
title: "01_background"
author: "Dominic Henry"
date: "28/06/2021"
output: html_document
---

The Department of Forestry, Fisheries and the Environment (DFFE) have established an online, open-access national Environmental Screening Tool (EST). As as of the 5th July 2019, by law, a report generated by the screening tool must accompany all environmental impact assessments (EIAs).

Amongst others, the purposes of the screening tool are to streamline and simplify the EIA process by providing timeous, succinct, and robust reports; to ensure ongoing improvement to the efficiency and effectiveness of the EIA process; to enable the applicant to avoid sensitive sites by manipulating the development footprint on a site, to avoid environmental sensitivities; and to identify upfront any specific exclusions, restrictions, prohibitions or exceptions to the EIA process that apply to a particular site. The screening tool also informs early stage decisions around avoidance, minimization, specialist requirements and, in some cases, early rejection of a proposed site as a viable development area.

The tool screens for a broad range of environmental sensitivities, including terrestrial plant and animal biodiversity. The South African Biodiversity Institute, Endangered Wildlife Trust, and BirdLife South Africa have collaborated to develop the species data that feeds into the screening tool. The criteria for inclusion of a species is that they are a species of conservation concern listed on the IUCN Red List of Threatened Species or South Africa's National Red List website as Critically Endangered, Endangered or Vulnerable according to the IUCN Red List 3.1. Categories and Criteria. There are currently over 340 animal and 4600 plant species represented in the screening tool. 

The spatial data in the screening tool is assigned one of three sensitivity levels: Very High, High, and Medium. Very High sensitivity is critical habitat for range restricted species of conservation concern that have a global range of less than 10 km^2^. High sensitivity is recent (post 2002) confirmed habitat for species of conservation concern, whereas Medium sensitivity is suspected habitat for species of conservation concern based either on there being occurrence records for this species collected in the past prior to 2002 or being a natural area included in a habitat suitability model. Click [here](https://www.environment.gov.za/sites/default/files/gazetted_notices/nema_environmentalthemes_reportingcriteria_g43110_gn320.pdf) to download the gazetted protocol for the assessment and reporting of environmental impacts on terrestrial animal and plant species.

In this threatened species no-go area tool we build on the foundation of the environmental screening tool to fill a number of important gaps.
