---
title: "02_purpose"
author: "Dominic Henry"
date: "28/06/2021"
output: html_document
---

This is a national scale application which informs prospective developers, Environmental Assessment practitioners and/or the general public about areas of very high sensitivity biodiversity importance based on threatened animal and plant data. The intended purpose of the tool is to inform the placement of proposed potentially detrimental developments in order to encourage early-stage rejection or avoidance before EIA commencement and in this way avoid unnecessary cost to the developer, the responding interested and affected parties (especially conservation agencies) and as a result reduce irreversible loss/risk to the environment. There has been hesitancy to identify areas which are highly unsuitable for development and this application aims to address this directly. From the perspective of threatened plant and animal diversity, this online app allows for rapid assessment of site sensitivity to inform the first stage of the mitigation hierarchy, that being avoidance.

Our online tool has a number of features that make it well suited to addressing the issue of site sensitivity, namely:

***Rapid assessment and ease of use:*** while the environmental screening tool provides a comprehensive overview of all environmental sensitivities it does not allow for rapid assessment of the presence of threatened and range-restricted species. Reports generated by the screening tool can take several minutes to generate and some knowledge of EIAs and the types of developments are required before progressing to the mapping section of the screening tool. While no special training is technically required to use the tool, in our experience we have found that it is not intuitive and straightforward, especially for non-technical users. This is an impediment for interested and affected parties who are not active participants in the EIA sector. Our tool therefore allows for a quick visual inspection and identification of highly sensitive areas.

***Access to species level data:*** the screening tool does not allow for mapping of a species at its full spatial extent. Our application allows access to these data on a species-by-species basis. Never before has such an up to date and comprehensive data set on threatened species been collated and this tool brings prominence to this fact. The species in this tool are therefore brought to the foreground of conservation efforts.

***Multiple ways to identify sensitive areas:*** our application allows for multiple ways to identify whether a property contains a sensitive threatened species no-go area. These include uploading a shapefile/KML file, searching a property using the 21-digit SG code, entering a geographical point (specified using latitude and longitude), or using a hand-drawn shape directly onto the map.

It is important to note that the use of this tool provides a complementary approach to assess the potential impact of developments on our natural heritage. It is not a replacement for the other layers and tools currently in use.
